### ISSUE TITLE
input string was not in a correct format

### ISSUE THREAD

**Issue by cloudalina** [Andrewthe13th/Inventory_Kamera#112]
Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at InventoryKamera.WeaponScraper.ScanWeaponCount() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\WeaponScraper.cs:line 414
   at InventoryKamera.WeaponScraper.ScanWeapons(Int32 count) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\WeaponScraper.cs:line 18
   at InventoryKamera.InventoryKamera.GatherData(Boolean[] formats, Boolean[] checkbox) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 73
   at InventoryKamera.Form1.<>c__DisplayClass21_0.<StartButton_Clicked>b__0() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Form1.cs:line 207

**Comment by Andrewthe13th** [comment]
why did u close this. Did it work this time?
