### ISSUE TITLE
UIPI error

### ISSUE THREAD

**Issue by YukiRed** [Andrewthe13th/Inventory_Kamera#118]
So I got this error, what do i do?

Some simulated input commands were not sent successfully. The most common reason for this happening are the security features of Windows including User Interface Privacy Isolation (UIPI). Your application can only send commands to applications of the same or lower elevation. Similarly certain commands are restricted to Accessibility/UIAutomation applications. Refer to the project home page and the code samples for more information.
   at WindowsInput.WindowsInputMessageDispatcher.DispatchInput(INPUT[] inputs)
   at WindowsInput.KeyboardSimulator.KeyPress(VirtualKeyCode keyCode)
   at InventoryKamera.Navigation.InventoryScreen() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Navigation.cs:line 260
   at InventoryKamera.InventoryKamera.GatherData(Boolean[] formats, Boolean[] checkbox) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 71
   at InventoryKamera.Form1.<>c__DisplayClass21_0.<StartButton_Clicked>b__0() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Form1.cs:line 207

**Comment by Cupcak3** [comment]
Does Kamera ask for admin rights when you start the application? 

It is not possible for Kamera to run without admin rights because Genshin requires admin rights.

**Comment by Cupcak3** [comment]
I am closing this issue now. Please reopen the issue if you have further questions.
