### ISSUE TITLE
No items detected in inventory

### ISSUE THREAD

**Issue by Icy058** [Andrewthe13th/Inventory_Kamera#129]
The Kamera opens my inventory to scan for weapons, clicks the weapons tab, then throws this error.
No items detected in inventory
   at InventoryKamera.WeaponScraper.GetPageOfItems() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\WeaponScraper.cs:line 129
   at InventoryKamera.WeaponScraper.ScanWeapons(Int32 count) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\WeaponScraper.cs:line 19
   at InventoryKamera.InventoryKamera.GatherData(Boolean[] formats, Boolean[] checkbox) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 73
   at InventoryKamera.Form1.<>c__DisplayClass21_0.<StartButton_Clicked>b__0() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Form1.cs:line 207

I have restarted my game and ran the program as an admin. I'm also running Windows 11 if that makes a difference.

**Comment by Andrewthe13th** [comment]
make sure you have these files where the program lies 
![image](https://user-images.githubusercontent.com/11446437/147294610-cd04897f-27da-45cf-9a72-9576a454feee.png)

or else do this:
Select Options -> Update Lookup tables -> Select Everything -> Update
![image](https://user-images.githubusercontent.com/11446437/147294684-9215265f-f818-42a3-9f03-c47d26da5fbc.png)

**Comment by Cupcak3** [comment]
If you get that error it likely means that the size of the item icons are much smaller or much larger than expected. Can you share what the resolution of your monitor is and what window size you have Genshin running in? A screenshot of your whole monitor with the weapon inventory page open would also help.

**Comment by Cupcak3** [comment]
Hi there, this issue is hopefully resolved in [the v1.1.1 prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.1.1-prerelease). If it has been, please let us know so we can close this issue.

**Comment by Cupcak3** [comment]
I am going to close this issue as feedback hasn't been given in over a month. Recent releases have also improved on this issue as well. Please feel free to reopen or create a new issue if you continue to experience this problem.
