### ISSUE TITLE
Error when parsing character materials

### ISSUE THREAD

**Issue by ih8coffee** [Andrewthe13th/Inventory_Kamera#135]
I have tried reinstalling v c++, redownloading the tool. Neither have worked and I havent found a config file to trouble shoot the issue myself.

Sequence contains no elements
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at InventoryKamera.MaterialScraper.Scan_Materials(InventorySection section) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\MaterialScraper.cs:line 70
   at InventoryKamera.InventoryKamera.GatherData(Boolean[] formats, Boolean[] checkbox) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 120
   at InventoryKamera.Form1.<>c__DisplayClass21_0.<StartButton_Clicked>b__0() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Form1.cs:line 207

**Comment by Cupcak3** [comment]
Thanks for the report. Can you take a full window screenshot of the monitor with Genshin open to the inventory page that you experience this crash on?

**Comment by Cupcak3** [comment]
I am going to close this issue now as there has not been more information given in over two weeks. Please reopen the issue if you have any questions.
