### ISSUE TITLE
Scanner does not start up

### ISSUE THREAD

**Issue by rookyyy** [Andrewthe13th/Inventory_Kamera#148]
Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at InventoryKamera.WeaponScraper.ScanWeaponCount() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\WeaponScraper.cs:line 414
   at InventoryKamera.WeaponScraper.ScanWeapons(Int32 count) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\WeaponScraper.cs:line 18
   at InventoryKamera.InventoryKamera.GatherData(Boolean[] formats, Boolean[] checkbox) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 73
   at InventoryKamera.Form1.<>c__DisplayClass21_0.<StartButton_Clicked>b__0() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Form1.cs:line 207

**Comment by Cupcak3** [comment]
This probably means that the scanner could not determine the number of total weapons there as shown in the top right of the inventory tab. Do you see an image show up in the preview image around this area when the crash happens?
![image](https://user-images.githubusercontent.com/8845977/149022437-65da67a4-879a-47f8-bd53-cf9efdfb14a4.png)

**Comment by Cupcak3** [comment]
I am going to close this issue as feedback has not been given in over a month. Please feel free to reopen or create a new issue if you still experience this problem.
