### ISSUE TITLE
App stop working during scan

### ISSUE THREAD

**Issue by erksnowy** [Andrewthe13th/Inventory_Kamera#151]

**Comment by erksnowy** [comment]
![image](https://user-images.githubusercontent.com/42830737/147820016-be0cd09b-5971-47c6-8c90-229086bc32d6.png)

**Comment by xavierwg13** [comment]
App hangs on Kokomi's name. This happened to me as well.

**Comment by KimZaOnLinE** [comment]
Error Log

Could not determine character's name or element
Object reference not set to an instance of an object.
   at InventoryKamera.CharacterScraper.ScanCharacters() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\CharacterScraper.cs:line 23
   at InventoryKamera.InventoryKamera.GatherData(Boolean[] formats, Boolean[] checkbox) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 94
   at InventoryKamera.Form1.<>c__DisplayClass21_0.<StartButton_Clicked>b__0() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Form1.cs:line 207

**Comment by sumiranpradhan** [comment]
Yep same here.

**Comment by Estasi0** [comment]
I'm having a similar issue while scanning(1.1), it stop halfway through without any error log so I tried a previous version (1.0) but it stopped just before saving the file. I tried this over on other PCs cause I thought maybe something was wrong with mine but had the same issue with both versions. Just to be clear I previously used 1.0 and it worked just fine IDK why it's not working now. Please fix it I love this tool it made my life much easier. I really appreciate what yall are doing.

**Comment by Cupcak3** [comment]
Hi there. There was a bug when IK tried to scan characters with names that wrapped lines in the top left corner. If this bug happened before 4 characters had been scanned, another bug occurred. These issues are hopefully resolved in [the v1.1.1 prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.1.1-prerelease).  If they have been, please let us know so we can close this issue.
