### ISSUE TITLE
Error Log

### ISSUE THREAD

**Issue by alexsoumi** [Andrewthe13th/Inventory_Kamera#155]
The type initializer for 'InventoryKamera.Scraper' threw an exception.
   at InventoryKamera.Scraper.RestartEngines()
   at InventoryKamera.InventoryKamera.GatherData(Boolean[] formats, Boolean[] checkbox) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 59
   at InventoryKamera.Form1.<>c__DisplayClass21_0.<StartButton_Clicked>b__0() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Form1.cs:line 207

**Comment by Cupcak3** [comment]
Hi there. Please check out the [v1.2.1-prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.1-prereleasehttps://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.1-prerelease). It has a possible fix aimed specifically to fix this issue.

**Comment by Cupcak3** [comment]
Please check out the note in the latest release patch notes. One user found that installing both the [x64 and x86 C++ 2015-2022 (or 2019) redistributable packages from Microsoft](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022) fixed this error.

![image](https://user-images.githubusercontent.com/8845977/154861603-e6387622-c351-414e-bee3-24c3a6bcfdc6.png)
