### ISSUE TITLE
character error

### ISSUE THREAD

**Issue by koshicae** [Andrewthe13th/Inventory_Kamera#156]
the scanner stopped after scanning cons (which were none) and talents (7-7-7) for the first character (hu tao)
the error log was:

Object reference not set to an instance of an object.
   at InventoryKamera.CharacterScraper.ScanCharacters() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\CharacterScraper.cs:line 23
   at InventoryKamera.InventoryKamera.GatherData(Boolean[] formats, Boolean[] checkbox) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 94
   at InventoryKamera.Form1.<>c__DisplayClass21_0.<StartButton_Clicked>b__0() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Form1.cs:line 207

**Comment by Cupcak3** [comment]
Hi there, this issue is hopefully resolved in [the v1.1.1 prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.1.1-prerelease). If it has been, please let us know so we can close this issue.
