### ISSUE TITLE
Crash error after scanning artifacts and enter character page

### ISSUE THREAD

**Issue by clanchestonly** [Andrewthe13th/Inventory_Kamera#167]
Object reference not set to an instance of an object.
   at InventoryKamera.CharacterScraper.ScanCharacters() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\CharacterScraper.cs:line 23
   at InventoryKamera.InventoryKamera.GatherData(Boolean[] formats, Boolean[] checkbox) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 94
   at InventoryKamera.Form1.<>c__DisplayClass21_0.<StartButton_Clicked>b__0() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Form1.cs:line 207

could it be due to shen he being a new character?

**Comment by Cupcak3** [comment]
This crash is likely a combination of a known bug as well as shenhe being a new character. [V1.1.1 prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.1.1-prerelease) has a fix for the bug and comes prepackaged with the new items and characters that were added in the version 2.4 update.
