### ISSUE TITLE
Scans one character, auto-attacks then goes to profile picture menu

### ISSUE THREAD

**Issue by domi-domi-domi** [Andrewthe13th/Inventory_Kamera#168]
When trying to scan characters, 
- the first character is scanned, but not completely (the 3 last pictures under 'character' int he kamera interface are from the overworld and not the character menu)
- it then returns to the normal world by exiting character menu
- performs a few auto-attacks
- goes to esc menu and clicks on profile picture, bringing up the menu to change it
- keeps on "scanning" but stays frozen on the profile picture interface

I tried 1280x720 and 1280x800, and can scan weapons and materials fine (altough some are missing from the final json). Since there is no error, there are no screenshots to log. I can gladly perfom additionnal tests if needed.

**Comment by Andrewthe13th** [comment]
few auto attacks means you need to rebind your keys or change the keybinding under options in this application.

**Comment by z4ck38** [comment]
I am seeing the same behavior. 

I have verified the key bindings for character and inventory are set to C and B respectively in both the game and the application. 

When scanning the following happens:

-Traveler name is not scanned correctly
-Artifacts appear to be scanned correctly
-The first character is scanned, but the screenshots to the left of the character output window appear to be wrong. 
-Then the scanner presses escape and freezes on the profile picture

I am also seeing the following errors in the log:

(Note: I do not have a drive labeled as B:)

Input string was not in a correct format.

   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)


   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)


   at InventoryKamera.WeaponScraper.ScanWeaponCount() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\WeaponScraper.cs:line 467


   at InventoryKamera.WeaponScraper.ScanWeapons(Int32 count) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\WeaponScraper.cs:line 22


   at InventoryKamera.InventoryKamera.GatherData() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 80
