### ISSUE TITLE
Issue with scanning Yun Jin and Shenhe

### ISSUE THREAD

**Issue by kingsjustice** [Andrewthe13th/Inventory_Kamera#169]
The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at InventoryKamera.CharacterScraper.ScanCharacter(Character& character) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\CharacterScraper.cs:line 107
   at InventoryKamera.CharacterScraper.ScanCharacters() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\CharacterScraper.cs:line 21
   at InventoryKamera.InventoryKamera.GatherData(Boolean[] formats, Boolean[] checkbox) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 94
   at InventoryKamera.Form1.<>c__DisplayClass21_0.<StartButton_Clicked>b__0() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Form1.cs:line 207

Able to scan entire account however when it reaches Yun Jin it gives this error message. I'm assuming because it doesn't recognize the character information however beforehand it would just copy it down as Venti and carry on.

**Comment by Cupcak3** [comment]
We have given users the capability to update Kamera with new items and characters in the application. You can do this with the update feature under `options`.

We plan to make this more automatic in the future. Additionally, [the v1.1.1 prerelease](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.1.1-prerelease) comes prepackaged with the new items and characters from the version 2.4 update if you would like to use that.
