### ISSUE TITLE
After The update i tried to scan my stuff but it didn't work and it always says this:

### ISSUE THREAD

**Issue by Jukylije** [Andrewthe13th/Inventory_Kamera#170]
The type initializer for 'InventoryKamera.Scraper' threw an exception.
   at InventoryKamera.Scraper.RestartEngines()
   at InventoryKamera.InventoryKamera.GatherData(Boolean[] formats, Boolean[] checkbox) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 59
   at InventoryKamera.Form1.<>c__DisplayClass21_0.<StartButton_Clicked>b__0() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Form1.cs:line 207

**Comment by Cupcak3** [comment]
Please check out [the latest release](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2) and let us know if this issue has been resolved.

**Comment by Cupcak3** [comment]
Please make sure you install **both** the [x64 and x86 C++ 2015-2022 (or 2019) redistributable packages from Microsoft](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022).
