### ISSUE TITLE
Any Idea what this means?

### ISSUE THREAD

**Issue by Rilasis** [Andrewthe13th/Inventory_Kamera#178]
Genshin's window width cannot be 0

   at InventoryKamera.Navigation.GetAspectRatio() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Navigation.cs:line 127

   at InventoryKamera.Form1.<StartButton_Clicked>b__12_0() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Form1.cs:line 169

**Comment by Cupcak3** [comment]
Most of the time this means that Genshin is in some sort of fullscreen mode. The scanner only works in windowed modes for now.

**Comment by Rilasis** [comment]
Gotcha, thank you. I got it to work by clicking on Genshin as soon as I clicked scan in the scanner.
