### ISSUE TITLE
1.2 Kamera Unable to scan due to errors such as

### ISSUE THREAD

**Issue by Jayboss15** [Andrewthe13th/Inventory_Kamera#182]
System.IO.FileNotFoundException: Could not load file or assembly 'WindowsInput, Version=1.0.4.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad' or one of its dependencies. The system cannot find the file specified.
File name: 'WindowsInput, Version=1.0.4.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad'
   at InventoryKamera.Form1.UpdateKeyTextBoxes()
   at InventoryKamera.Form1.Form1_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

AND

System.IO.FileNotFoundException: Could not load file or assembly 'NHotkey.WindowsForms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=a76ffb086700b11c' or one of its dependencies. The system cannot find the file specified.
File name: 'NHotkey.WindowsForms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=a76ffb086700b11c'
   at InventoryKamera.Form1.StartButton_Clicked(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

I am a student in software development but I'm just starting out so all I can get from this is that im missing windows files
Do i need recover my windows files to get it to work?

**Comment by Cupcak3** [comment]
These are included in the zip file you should not need to go and download them separately.
![image](https://user-images.githubusercontent.com/8845977/151270499-48bc9644-382a-4767-b6be-c5c6a7165381.png)

**Comment by Jayboss15** [comment]
Ah, I took it out of the folder for ease of access without unzipping the folder, Thanks for the help!
