### ISSUE TITLE
Radeon Image Sharpening affecting scanning

### ISSUE THREAD

**Issue by R3nierjvr** [Andrewthe13th/Inventory_Kamera#199]
eveerything fails to scan except for characters , having simmiliar issues with other scanners. they scan but everything is in correct.

Using the latest Release screen set to 1600x900
Below the screenshots for Artifacts , inventory and weapons

The log details here :

Insufficient items found in weapon inventory

   at InventoryKamera.WeaponScraper.GetPageOfItems() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\WeaponScraper.cs:line 154

   at InventoryKamera.WeaponScraper.ScanWeapons(Int32 count) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\WeaponScraper.cs:line 23

   at InventoryKamera.InventoryKamera.GatherData() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 80

Insufficient items found in artifact inventory

   at InventoryKamera.ArtifactScraper.GetPageOfItems() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\ArtifactScraper.cs:line 186

   at InventoryKamera.ArtifactScraper.ScanArtifacts(Int32 count) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\ArtifactScraper.cs:line 23

   at InventoryKamera.InventoryKamera.GatherData() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 96

Sequence contains no elements

   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)

   at InventoryKamera.MaterialScraper.Scan_Materials(InventorySection section, HashSet`1& materials) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\MaterialScraper.cs:line 105

   at InventoryKamera.InventoryKamera.GatherData() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 146

Sequence contains no elements

   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)

   at InventoryKamera.MaterialScraper.Scan_Materials(InventorySection section, HashSet`1& materials) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\MaterialScraper.cs:line 105

   at InventoryKamera.InventoryKamera.GatherData() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 164

Please help

Thank you in advance

**Comment by R3nierjvr** [comment]
![ArtifactInventory](https://user-images.githubusercontent.com/26996566/152174322-8c918d8c-d8ba-4673-b30d-f030a1502b5d.png)
![mora](https://user-images.githubusercontent.com/26996566/152174353-e35c4b21-c6f5-413d-a9d2-28b44a539331.png)
![WeaponInventory](https://user-images.githubusercontent.com/26996566/152174369-23ddcddd-f374-4c67-b4a5-e8237e8d649c.png)

**Comment by R3nierjvr** [comment]
Did get  a reply but found the issue . Image sharpening ......

![image](https://user-images.githubusercontent.com/26996566/152406544-cfce4d63-b834-4513-a641-8e6415d5a79d.png)

Turned it off and all working now, who would have known....

**Comment by ndo** [comment]
This issue is still open and I have the same issue.

Resolution: 1680x1050 Windowed

The characters scan, but not everything else.  It would at most visit the correct screen, but not scan the items.

I use an Nvidia card, so I'm not sure if I have anything like "image sharpening".

Insufficient items found in weapon inventory

   at InventoryKamera.WeaponScraper.GetPageOfItems() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\WeaponScraper.cs:line 154


   at InventoryKamera.WeaponScraper.ScanWeapons(Int32 count) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\WeaponScraper.cs:line 23


   at InventoryKamera.InventoryKamera.GatherData() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 80


Insufficient items found in artifact inventory

   at InventoryKamera.ArtifactScraper.GetPageOfItems() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\ArtifactScraper.cs:line 186


   at InventoryKamera.ArtifactScraper.ScanArtifacts(Int32 count) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\ArtifactScraper.cs:line 23


   at InventoryKamera.InventoryKamera.GatherData() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 96


Insufficient items found in CharacterDevelopmentItems inventory

   at InventoryKamera.MaterialScraper.GetPageOfItems(InventorySection section) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\MaterialScraper.cs:line 271


   at InventoryKamera.MaterialScraper.Scan_Materials(InventorySection section, HashSet`1& materials) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\MaterialScraper.cs:line 67


   at InventoryKamera.InventoryKamera.GatherData() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 146


Insufficient items found in Materials inventory

   at InventoryKamera.MaterialScraper.GetPageOfItems(InventorySection section) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\MaterialScraper.cs:line 271


   at InventoryKamera.MaterialScraper.Scan_Materials(InventorySection section, HashSet`1& materials) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\MaterialScraper.cs:line 67

   at InventoryKamera.InventoryKamera.GatherData() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 164

The images from the log folder is just black:

Weapon:
![WeaponInventory](https://user-images.githubusercontent.com/1386444/152443294-0268cde3-001e-4e27-8b3b-a6da9fe545ce.png)

Artifact:
![ArtifactInventory](https://user-images.githubusercontent.com/1386444/152443349-98fc4e6a-6b2c-47f4-bd33-1f7d17c524fa.png)

Character Development Items:
![CharacterDevelopmentItemsInventory](https://user-images.githubusercontent.com/1386444/152443370-effd8a60-8517-415c-878a-50413b7e1bd7.png)

Materials:
![MaterialsInventory](https://user-images.githubusercontent.com/1386444/152443377-cec41405-d5d3-48c4-a772-1de70f972ce9.png)

Except for Mora:
![mora](https://user-images.githubusercontent.com/1386444/152443394-7cbda96f-c1f7-47db-aa97-bbcf609029d9.png)

**Comment by R3nierjvr** [comment]
Maybe check Reshade, Windows Night Light, F.lux, Nvidia Filters and Colourblind compensation tools.
anything that effects resolution ect. If your getting a black screen somthing is interfering with the game capture. Only thing I can think of.

**Comment by Cupcak3** [comment]
@R3nierjvr is correct. There are many things that have the possibility to interfere with the screen capture. If you have any image enhancement software that affects Genshin please let us know what they are. The Windows image capturing and processing pipeline is a bit new to me so I don't have the knowledge to guess as to what and how something is causing the screenshots to be completely black.
