### ISSUE TITLE
Error when trying to scan

### ISSUE THREAD

**Issue by ShiinaRio** [Andrewthe13th/Inventory_Kamera#205]
Insufficient items found in CharacterDevelopmentItems inventory

   at InventoryKamera.MaterialScraper.GetPageOfItems(InventorySection section) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\MaterialScraper.cs:line 271

   at InventoryKamera.MaterialScraper.Scan_Materials(InventorySection section, HashSet`1& materials) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\MaterialScraper.cs:line 67

   at InventoryKamera.InventoryKamera.GatherData() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 146

**Comment by Cupcak3** [comment]
As your other issue #210 is a bit more detailed I will close this issue in favor of continuing with that issue.
