### ISSUE TITLE
Getting an error when trying to scan

### ISSUE THREAD

**Issue by josephisticated** [Andrewthe13th/Inventory_Kamera#207]
Genshin's window width cannot be 0

   at InventoryKamera.Navigation.GetAspectRatio() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Navigation.cs:line 127

   at InventoryKamera.Form1.<StartButton_Clicked>b__12_0() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Form1.cs:line 169

--------------------------------------
Up there is the log I'm getting, my computer's resolution is 1600x900.

**Comment by josephisticated** [comment]
Solved this by getting my game's resolution down to 1280x720. 1600x900 support or a warning that would tell us the other resolutions that would work would be nice.

**Comment by Cupcak3** [comment]
1600x900 is supported. The `width cannot be 0` error likely means your game was in a fullscreen mode/disappeared. All 16:9 and 16:10 aspect ratio resolutions are supported but 4K resolutions have been reported to break functionality a little.
