### ISSUE TITLE
Error while scrapping Materials tab

### ISSUE THREAD

**Issue by jfothergill** [Andrewthe13th/Inventory_Kamera#213]
Insufficient items found in Materials inventory

   at InventoryKamera.MaterialScraper.GetPageOfItems(InventorySection section) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\MaterialScraper.cs:line 271

   at InventoryKamera.MaterialScraper.Scan_Materials(InventorySection section, HashSet`1& materials) in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\MaterialScraper.cs:line 67

   at InventoryKamera.InventoryKamera.GatherData() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 164

**Comment by Cupcak3** [comment]
Please check out the [V1.2.2 release](https://github.com/Andrewthe13th/Inventory_Kamera/releases/tag/v1.2.2). It has fixes aimed to solve this problem. Let us know if the it fixes the problem so that we can close this issue.
