### ISSUE TITLE
Scan fails to run

### ISSUE THREAD

**Issue by xunlinkx** [Andrewthe13th/Inventory_Kamera#218]
1920x1080 windowed, I_K to the side of the window
logged in, started game, clicked controls -> keyboard, hit esc to paimon menu.

The type initializer for 'InventoryKamera.Scraper' threw an exception.
   at InventoryKamera.Scraper.RestartEngines()
   at InventoryKamera.InventoryKamera.GatherData() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 66
   at InventoryKamera.Form1.<StartButton_Clicked>b__12_0() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Form1.cs:line 180

**Comment by xunlinkx** [comment]
Nevermind, it ...ran ... after I ran the ADeptiScanner, then retried this one...semed to work
also made resolution 1600x900.
