### ISSUE TITLE
Type initializer threw an exception

### ISSUE THREAD

**Issue by Rilasis** [Andrewthe13th/Inventory_Kamera#235]
The type initializer for 'InventoryKamera.Scraper' threw an exception.

   at InventoryKamera.Scraper.RestartEngines()

   at InventoryKamera.InventoryKamera.GatherData() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\InventoryKamera.cs:line 66

   at InventoryKamera.Form1.<StartButton_Clicked>b__12_0() in B:\Projects\VisualStudio\InventoryKamera\InventoryKamera\InventoryKamera\Form1.cs:line 180

**Comment by Cupcak3** [comment]
[#126](https://github.com/Andrewthe13th/Inventory_Kamera/issues/126#issuecomment-1031993729). Please make sure you install **both** the [x64 and x86 C++ 2015-2022 (or 2019) redistributable packages from Microsoft](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022).
