### ISSUE TITLE
Failed to find library "leptonica-1.80.0.dll" for platform x86. Installed both Microsoft Visual C x86 and x64 packages so not sure why this is happening.

### ISSUE THREAD

**Issue by LeifaChan** [Andrewthe13th/Inventory_Kamera#287]
System.DllNotFoundException: Failed to find library "leptonica-1.80.0.dll" for platform x86.

   at InteropDotNet.LibraryLoader.LoadLibrary(String fileName, String platformName)

   at InteropRuntimeImplementer.LeptonicaApiSignaturesInstance.LeptonicaApiSignaturesImplementation..ctor(LibraryLoader loader)

**Comment by Cupcak3** [comment]
This file is unrelated to the Microsoft Visual C packages. It is provided already in the x64 and x84 folders with each download. Make sure all the contents from the zip are extracted.

**Comment by rispi23** [comment]
I got the same problem and I compared the zip with the extracted files already, does anyone know if the original commenter got a solution?

**Comment by Cupcak3** [comment]
The only solution is to verify you have the files under the x64 and x86 folders in the downloaded zip file. They are provided in the release zip folder and that zip must be extracted to a folder of your choosing on your computer

**Comment by baaaaalllllsss** [comment]
i have the same issue and i checked the x86 folder and it contains "leptonica-1.80.0.dll" and "tesseract41.dll", yet i still get "scan aborted" and "Failed to find library "leptonica-1.80.0.dll" for platform x86."

**Comment by DoolenDev** [comment]
any updates on this? I am having this same issue and cannot find anything.

**Comment by Cupcak3** [comment]
https://github.com/Andrewthe13th/Inventory_Kamera/issues/400#issuecomment-1314615342
Please try see this comment thread
