### ISSUE TITLE
Tesseract Exception When Trying to Update

### ISSUE THREAD

**Issue by spicytiff** [Andrewthe13th/Inventory_Kamera#366]
### Current Behavior

I have one successful scan of everything and am trying to do an updated scan. However, when trying to start the scan, I get this error:
`Tesseract.TesseractException: Failed to initialise tesseract engine.. See https://github.com/charlesw/tesseract/wiki/Error-1 for details.

   at Tesseract.TesseractEngine.Initialise(String datapath, String language, EngineMode engineMode, IEnumerable`1 configFiles, IDictionary`2 initialValues, Boolean setOnlyNonDebugVariables)

   at Tesseract.TesseractEngine..ctor(String datapath, String language, EngineMode engineMode, IEnumerable`1 configFiles, IDictionary`2 initialOptions, Boolean setOnlyNonDebugVariables)

   at InventoryKamera.Scraper.InitEngines()

   at InventoryKamera.Scraper..cctor()

`

### Expected Behavior

The scanner continues to scan

### Reproducing a Behavior

![image](https://user-images.githubusercontent.com/75649038/187010425-de016ae6-ff2e-4556-8896-1b759cfa83ce.png)

Attempt a secondary scan in same or different folder where the first scan was exported to? No other changes were made to Inventory Kamera settings.

### Device OS

Windows 11

### Genshin Impact Version

3.0

### Inventory Kamera Version

1.2.8

### Screen resolution, screen mode, and UI scale

1920x1200 Windowed

### Additional notes and remarks

I checked the github link for Error-1 but unfortunately I do not understand what the issue is and how to fix it.

### Evidence

```
Tesseract.TesseractException: Failed to initialise tesseract engine.. See https://github.com/charlesw/tesseract/wiki/Error-1 for details.


   at Tesseract.TesseractEngine.Initialise(String datapath, String language, EngineMode engineMode, IEnumerable`1 configFiles, IDictionary`2 initialValues, Boolean setOnlyNonDebugVariables)


   at Tesseract.TesseractEngine..ctor(String datapath, String language, EngineMode engineMode, IEnumerable`1 configFiles, IDictionary`2 initialOptions, Boolean setOnlyNonDebugVariables)


   at InventoryKamera.Scraper.InitEngines()


   at InventoryKamera.Scraper..cctor()



```

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Ceredril** [comment]
I am facing the same issue, but it only started after updating the data set to 3.0

**Comment by Ceredril** [comment]
Apparently this issue persists with V1.3, however it only appears after opening the Scanner the SECOND time after installing it.

temporary fix: deleting the scanner folder and extracting it again from the zip file every time the application is to be opened.
This suggests some form of file corruption happening.

**Comment by marviny2** [comment]
im experiencing the same issue on V1.3 but it happens every time i open it
