### ISSUE TITLE
Material scan error

### ISSUE THREAD

**Issue by eassedou** [Andrewthe13th/Inventory_Kamera#372]
### Current Behavior

Sequence contains no elements

   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)

   at InventoryKamera.MaterialScraper.ScanMaterialCount(Rectangle rectangle, Bitmap& quantity)

   at InventoryKamera.MaterialScraper.Scan_Materials(InventorySection section, Inventory& inventory)

   at InventoryKamera.InventoryKamera.GatherData()

Sequence contains no elements

   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)

   at InventoryKamera.MaterialScraper.ScanMaterialCount(Rectangle rectangle, Bitmap& quantity)

   at InventoryKamera.MaterialScraper.Scan_Materials(InventorySection section, Inventory& inventory)

   at InventoryKamera.InventoryKamera.GatherData()

### Expected Behavior

The scanner continues to scan

### Reproducing a Behavior

scan for materials

### Device OS

Windows 11

### Genshin Impact Version

3.0

### Inventory Kamera Version

1.3

### Screen resolution, screen mode, and UI scale

1920x1080

### Additional notes and remarks

Sequence contains no elements

   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)

   at InventoryKamera.MaterialScraper.ScanMaterialCount(Rectangle rectangle, Bitmap& quantity)

   at InventoryKamera.MaterialScraper.Scan_Materials(InventorySection section, Inventory& inventory)

   at InventoryKamera.InventoryKamera.GatherData()

Sequence contains no elements

   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)

   at InventoryKamera.MaterialScraper.ScanMaterialCount(Rectangle rectangle, Bitmap& quantity)

   at InventoryKamera.MaterialScraper.Scan_Materials(InventorySection section, Inventory& inventory)

   at InventoryKamera.InventoryKamera.GatherData()

### Evidence

Sequence contains no elements

   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)

   at InventoryKamera.MaterialScraper.ScanMaterialCount(Rectangle rectangle, Bitmap& quantity)

   at InventoryKamera.MaterialScraper.Scan_Materials(InventorySection section, Inventory& inventory)

   at InventoryKamera.InventoryKamera.GatherData()

Sequence contains no elements

   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)

   at InventoryKamera.MaterialScraper.ScanMaterialCount(Rectangle rectangle, Bitmap& quantity)

   at InventoryKamera.MaterialScraper.Scan_Materials(InventorySection section, Inventory& inventory)

   at InventoryKamera.InventoryKamera.GatherData()

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [X] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by MasterEric** [comment]
Got the same error myself:

```
Failed to parse quantity for RobustFungalNucleus


Sequence contains no elements

   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)


   at InventoryKamera.MaterialScraper.ScanMaterialCount(Rectangle rectangle, Bitmap& quantity)


   at InventoryKamera.MaterialScraper.Scan_Materials(InventorySection section, Inventory& inventory)


   at InventoryKamera.InventoryKamera.GatherData()


Sequence contains no elements

   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)


   at InventoryKamera.MaterialScraper.ScanMaterialCount(Rectangle rectangle, Bitmap& quantity)


   at InventoryKamera.MaterialScraper.Scan_Materials(InventorySection section, Inventory& inventory)


   at InventoryKamera.InventoryKamera.GatherData()

```
