### ISSUE TITLE
Scan aborted right away

### ISSUE THREAD

**Issue by yoli19** [Andrewthe13th/Inventory_Kamera#379]
### Current Behavior

![Screenshot (134)](https://user-images.githubusercontent.com/100238381/188950741-0a635447-8dfa-4beb-921a-efd539361181.png)
Once I click 'Scan Genshin' it immediately gives me a 'Scan aborted' message and 2 error logs. 
 at InventoryKamera.Scraper.InitEngines()
 at InventoryKamera.Scraper..cctor()

### Expected Behavior

The scanner continues to scan

### Reproducing a Behavior

I'm not sure. I used the scanner a few weeks ago and it worked fine. Now it wont scan. 

### Device OS

Windows 10

### Genshin Impact Version

3.0

### Inventory Kamera Version

1.2.6

### Screen resolution, screen mode, and UI scale

1920x1080

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [X] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by yoli19** [comment]
I ended up reinstalling and it fixed the issue
