### ISSUE TITLE
Scan Abort - Failed Tesseract engine initialisation

### ISSUE THREAD

**Issue by nbrandtner-tgm** [Andrewthe13th/Inventory_Kamera#388]
### Current Behavior

Ok so I've used Inventory Kamera before, set it up again the exact same way, updated it for 3.1 and then wanted to start scanning. Kept getting "Scan aborted" above the Scan button after 1 second or so. I tried changing the scan options, reinstalling inventory kamera, repairing my Microsoft Visual C++ Redistributable and switching resolution of genshin impact to 1600:900 still same results. The exact Error log is this:

2022-10-01 18:48:22.882|ERROR|UserInterface|Tesseract.TesseractException: Failed to initialise tesseract engine.. See https://github.com/charlesw/tesseract/wiki/Error-1 for details.
   at Tesseract.TesseractEngine.Initialise(String datapath, String language, EngineMode engineMode, IEnumerable`1 configFiles, IDictionary`2 initialValues, Boolean setOnlyNonDebugVariables)
   at Tesseract.TesseractEngine..ctor(String datapath, String language, EngineMode engineMode, IEnumerable`1 configFiles, IDictionary`2 initialOptions, Boolean setOnlyNonDebugVariables)
   at InventoryKamera.Scraper.InitEngines()
   at InventoryKamera.Scraper..cctor()
2022-10-01 18:48:22.882|INFO|MainForm|Hotkey removed

I don't know what else to do. These are my current settings
![image_2022-10-01_190142752](https://user-images.githubusercontent.com/73284390/193420165-7cb0ec04-5161-42ab-944a-5bfbde061eda.png)

### Expected Behavior

The scanner continues to scan

### Reproducing a Behavior

I dont really know what causes this bug to show up so i dont have a clue how to reproduce it ig?

### Device OS

Windows 10

### Genshin Impact Version

3.1

### Inventory Kamera Version

1.3

### Screen resolution, screen mode, and UI scale

Tried different ones, default is 1920x1080 Fullscreen, as mentioned above i tried 1600x900 too

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by Cupcak3** [comment]
An issue for this problem already exists so I am closing this issue as a duplicate
