### ISSUE TITLE
Unable to update game data. Please check log for more details

### ISSUE THREAD

**Issue by josephcaroe** [Andrewthe13th/Inventory_Kamera#421]
### Current Behavior

So as title, i've downloaded Inventory Kamera and as soon as I started it, it promped me to update the item/character/artifact database so I clicked yes. And then it gave me this error.

So i tried opening the logs but it's still a mystery to me.

### Expected Behavior

The scanner to supports game new or edited content

### Reproducing a Behavior

Basically just going options => Update lookup tables. I already tried executing the .exe with OS privileges.

### Device OS

Windows 11

### Genshin Impact Version

3.3

### Inventory Kamera Version

1.3.5

### Screen resolution, screen mode, and UI scale

1920x1080, fullscreen

### Evidence

Image 1 of the error
![image](https://user-images.githubusercontent.com/14345195/211056225-e771066a-7e4a-4906-8918-0ed2122827bf.png)

This is the log
![image](https://user-images.githubusercontent.com/14345195/211056359-dddbd33a-a75a-4bd3-8453-08f24ca5e60f.png)

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [ ] I have attached the error log to the bug report.
- [ ] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by dev0T** [comment]
### Device OS

Windows 11

### Genshin Impact Version

3.3
![image](https://user-images.githubusercontent.com/28127196/211100036-9d3f7b55-5b19-49ec-8ed2-1d7f59276a2e.png)


### Inventory Kamera Version
1.3.5

### Screen resolution, screen mode, and UI scale

1440x900, windowed

### Evidence

Error image
![image](https://user-images.githubusercontent.com/28127196/211100298-97476ca3-d028-4b55-9d32-fee082a4f8e9.png)

My current log
```
2023-01-06 12:54:58.866|INFO|InventoryKamera|Kamera initialized
2023-01-06 12:54:59.680|INFO|MainForm|Inventory Kamera version 1.3.5
2023-01-06 12:54:59.686|INFO|MainForm|MainForm initialization complete
2023-01-06 12:54:59.846|INFO|DatabaseManager|Checking for newer game data...
2023-01-06 12:55:03.739|INFO|DatabaseManager|Forcing update for game data
2023-01-06 12:55:03.940|INFO|DatabaseManager|Updating Characters
2023-01-06 12:55:03.940|INFO|DatabaseManager|Updating Weapons
2023-01-06 12:55:03.940|INFO|DatabaseManager|Updating Artifacts
2023-01-06 12:55:03.940|INFO|DatabaseManager|Updating Materials
2023-01-06 12:55:04.244|INFO|DatabaseManager|Finished updating Weapons (Success)
2023-01-06 12:55:04.492|ERROR|DatabaseManager|Failed to update Materials data
2023-01-06 12:55:04.492|INFO|DatabaseManager|Finished updating Materials (Fail)
2023-01-06 12:55:04.492|ERROR|DatabaseManager|Failed to update Materials data
2023-01-06 12:55:18.889|INFO|DatabaseManager|Finished updating Characters (Success)
2023-01-06 12:55:19.384|INFO|DatabaseManager|Finished updating Artifacts (Success)
2023-01-06 12:55:19.384|ERROR|DatabaseManager|Could not update all information for version 3.3
2023-01-06 12:56:30.723|INFO|DatabaseManager|Updating Characters
2023-01-06 12:56:30.723|INFO|DatabaseManager|Updating Weapons
2023-01-06 12:56:30.723|INFO|DatabaseManager|Updating Artifacts
2023-01-06 12:56:30.723|INFO|DatabaseManager|Updating Materials
2023-01-06 12:56:30.986|INFO|DatabaseManager|Finished updating Weapons (Skipped)
2023-01-06 12:56:32.812|ERROR|DatabaseManager|Failed to update Materials data
2023-01-06 12:56:32.812|INFO|DatabaseManager|Finished updating Materials (Fail)
2023-01-06 12:56:32.812|ERROR|DatabaseManager|Failed to update Materials data
2023-01-06 12:56:32.812|INFO|DatabaseManager|Finished updating Characters (Skipped)
2023-01-06 12:56:38.179|INFO|DatabaseManager|Finished updating Artifacts (Skipped)
2023-01-06 12:56:38.179|ERROR|DatabaseManager|Could not update all information for version 0.0
2023-01-06 13:03:41.791|INFO|DatabaseManager|Updating Characters
2023-01-06 13:03:41.791|INFO|DatabaseManager|Updating Weapons
2023-01-06 13:03:41.791|INFO|DatabaseManager|Updating Artifacts
2023-01-06 13:03:41.791|INFO|DatabaseManager|Updating Materials
2023-01-06 13:03:42.026|INFO|DatabaseManager|Finished updating Weapons (Skipped)
2023-01-06 13:03:42.863|ERROR|DatabaseManager|Failed to update Materials data
2023-01-06 13:03:42.863|INFO|DatabaseManager|Finished updating Materials (Fail)
2023-01-06 13:03:42.863|ERROR|DatabaseManager|Failed to update Materials data
2023-01-06 13:03:44.543|INFO|DatabaseManager|Finished updating Characters (Skipped)
2023-01-06 13:03:47.081|INFO|DatabaseManager|Finished updating Artifacts (Skipped)
2023-01-06 13:03:47.081|ERROR|DatabaseManager|Could not update all information for version 0.0
```

 ### Preflight Checklist
 
    * [x]  I have checked for similar issues in the issue page, and I have not found any similar to mine.
    * [x]  I am using the latest version of the scanner.
    * [x]  I tried setting the scanning delay to maximum, and it still doesn't work.
    * [ ]  I have attached the video recording to the bug report.
    * [x]  I have attached the error log to the bug report.
    * [x]  I am available to later explains the issue.
    * [x]  I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
    * [x]  I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by josephcaroe** [comment]
I did as you suggested and modified the title.
I tried closing and reopening the tool many times, same thing every time. Also, if I try to scan anyway, i get the following error (basically telling me to update the database):

System.FormatException: Data file for CharacterDevelopmentItems is invalid. Please try running the auto updater and try again.


   in InventoryKamera.DatabaseManager.GetList(ListType list)


   in InventoryKamera.Scraper.ReloadData()


   in InventoryKamera.Scraper..cctor()

**Comment by SonGokuSSJ** [comment]
The author just updated Inventory Kamera to a new version (1.3.6). From the sound of the change log it should fix the error you are getting. Maybe you can try the new version and report back if that fixed it for you?

**Comment by ema4hhh** [comment]
> 

I have the same problem and I downloaded 1.3.6 and I get the same error as them

**Comment by rafsawicki** [comment]
I have the same error message with version 1.3.8. However, the log seems to be different:

```
2023-06-08 09:44:23.829|INFO|InventoryKamera|Kamera initialized
2023-06-08 09:44:24.068|INFO|MainForm|Inventory Kamera version 1.3.8
2023-06-08 09:44:24.154|INFO|DatabaseManager|Checking for newer game data...
2023-06-08 09:44:26.216|INFO|DatabaseManager|Forcing update for game data
2023-06-08 09:44:26.402|INFO|DatabaseManager|Updating Characters
2023-06-08 09:44:26.402|INFO|DatabaseManager|Updating Artifacts
2023-06-08 09:44:26.402|INFO|DatabaseManager|Updating Weapons
2023-06-08 09:44:26.402|INFO|DatabaseManager|Updating Materials
2023-06-08 09:44:26.606|INFO|DatabaseManager|Finished updating Weapons (Success)
2023-06-08 09:44:26.814|INFO|DatabaseManager|Finished updating Materials (Success)
2023-06-08 09:44:31.024|ERROR|DatabaseManager|An error was encountered when gathering information for the character HtmlAgilityPack.HtmlNode
2023-06-08 09:44:31.024|ERROR|DatabaseManager|System.NullReferenceException: Object reference not set to an instance of an object.
   at InventoryKamera.DatabaseManager.<>c__DisplayClass32_0.<UpdateCharacters>b__2(List`1 entry)
2023-06-08 09:44:32.591|INFO|DatabaseManager|Finished updating Characters (Fail)
2023-06-08 09:44:32.591|ERROR|DatabaseManager|Failed to update Characters data
2023-06-08 09:44:33.550|INFO|DatabaseManager|Finished updating Artifacts (Success)
2023-06-08 09:44:33.550|ERROR|DatabaseManager|Could not update all information for version 3.7
```

A part of the detailed log where the error is occuring
```
2023-06-08 09:44:31.006|DEBUG|DatabaseManager|Sangonomiya Kokomi burst is leveled at constellation 3
2023-06-08 09:44:31.024|DEBUG|DatabaseManager|Thoma skill is leveled at constellation 3
2023-06-08 09:44:31.024|ERROR|DatabaseManager|An error was encountered when gathering information for the character HtmlAgilityPack.HtmlNode
2023-06-08 09:44:31.024|ERROR|DatabaseManager|System.NullReferenceException: Object reference not set to an instance of an object.
   at InventoryKamera.DatabaseManager.<>c__DisplayClass32_0.<UpdateCharacters>b__2(List`1 entry)
2023-06-08 09:44:31.119|DEBUG|DatabaseManager|Shenhe skill is leveled at constellation 3
2023-06-08 09:44:31.473|DEBUG|DatabaseManager|Xiangling burst is leveled at constellation 3
```

**Comment by Cupcak3** [comment]
The updater should be working currently.
