### ISSUE TITLE
Major Tesseract error

### ISSUE THREAD

**Issue by kurt22i** [Andrewthe13th/Inventory_Kamera#484]
### Current Behavior

Tesseract.TesseractException: Failed to initialise tesseract engine.. See https://github.com/charlesw/tesseract/wiki/Error-1 for details.

   at Tesseract.TesseractEngine.Initialise(String datapath, String language, EngineMode engineMode, IEnumerable`1 configFiles, IDictionary`2 initialValues, Boolean setOnlyNonDebugVariables)

   at InventoryKamera.GenshinProcesor.InitEngines() in C:\Users\veloz\Source\Repos\Inventory_Kamera_Main\InventoryKamera\scraping\GenshinProcesor.cs:line 165

   at InventoryKamera.GenshinProcesor..cctor() in C:\Users\veloz\Source\Repos\Inventory_Kamera_Main\InventoryKamera\scraping\GenshinProcesor.cs:line 91

### Expected Behavior

The scanner continues to scan

### Reproducing a Behavior

Click "scan genshin" with most recent version of inventory kamera and materials database on my computer.

### Device OS

Windows 10

### Genshin Impact Version

4.2

### Inventory Kamera Version

1.3.11

### Screen resolution, screen mode, and UI scale

1600x900 windowed, also tried 1980x1020 fullscreen

### Additional notes and remarks

it was working just a few weeks ago, only difference from then is the 4.2 update, but "tesseract" sounds more like some computery dependency thingy

### Evidence

in the behavior section

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled all screen filtering software or plugins (i.e. HDR, Image Sharpening) while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by kurt22i** [comment]
I'm gonna close this because reinstalling inventory kamera fixed it, but still quite weird

**Comment by kurt22i** [comment]
.
