### ISSUE TITLE
Characters not scanned 

### ISSUE THREAD

**Issue by Zamasu97** [Andrewthe13th/Inventory_Kamera#520]
### Current Behavior

During character scanning it only scans the active character, constelations and basic attack lv, then it stops
Console output is
```
Unable to locate Weapons item count.


Parameter is not valid.

   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)


   at InventoryKamera.Navigation.CaptureRegion(RECT region, PixelFormat format)


   at InventoryKamera.CharacterScraper.ScanTalents(Character character)


   at InventoryKamera.CharacterScraper.ScanCharacter(String firstCharacter)


   at InventoryKamera.CharacterScraper.ScanCharacters(List`1& Characters)


   at InventoryKamera.InventoryKamera.GatherData()



```

### Expected Behavior

The scanner continues to scan

### Reproducing a Behavior

Start scanner with Characters selected

### Device OS

Windows 11

### Genshin Impact Version

4.6

### Inventory Kamera Version

1.3.16

### Screen resolution, screen mode, and UI scale

1920x1200 windowed

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [ ] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled (or documented) all screen filtering software, plugins, and enhancements while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by cr4zyc4t** [comment]
I tested multiple times, it seems that scanner will stop if the game graphics settings does not set to 16:9 resolution
