### ISSUE TITLE
Inventory Kamera crashes while scanning artifacts or weapons

### ISSUE THREAD

**Issue by notaspirit** [Andrewthe13th/Inventory_Kamera#529]
### Current Behavior

When trying to scan weapons or artifacts only a few (3-5) get scanned before the InventoryKamera crashes.
The slower the speed the less items get scanned. 
However scanning materials works just fine. 

### Expected Behavior

The scanner continues to scan

### Reproducing a Behavior

1. Select to scan weapons or artifacts
2. Start the scan
3. Let it run until it crashes

### Device OS

Windows 11

### Genshin Impact Version

4.7

### Inventory Kamera Version

1.3.16

### Screen resolution, screen mode, and UI scale

2560x1440 Borderless

### Additional notes and remarks

Tried reinstalling InventoryKamera, didn't fix the problem. 

### Evidence

https://github.com/user-attachments/assets/2bf33f36-93bf-451e-ba85-9612746ae7d0
For this demonstration the game is in borderless fullscreen on the main monitor (2560x1440) with the scanner on the second monitor

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [X] I have attached the video recording to the bug report.
- [ ] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled (or documented) all screen filtering software, plugins, and enhancements while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by flashkiller999** [comment]
Hello,

I am having the exact same issue.

I also the log files in the folder "logging" but no error is logged.

In the Eventlog however I was able to find the following errors:

**Error Message 1:**
> Application: InventoryKamera.exe
> Framework Version: v4.0.30319
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.ArgumentException
>    at System.ThrowHelper.ThrowArgumentException(System.ExceptionResource)
>    at System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Insert(System.__Canon, System.__Canon, Boolean)
>    at InventoryKamera.GenshinProcesor.FindClosestCharacterName(System.String, Int32)
>    at InventoryKamera.WeaponScraper.ScanEquippedCharacter(System.Drawing.Bitmap)
>    at InventoryKamera.WeaponScraper+<>c__DisplayClass6_0.<CatalogueFromBitmapsAsync>b__3()
>    at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
>    at System.Threading.Tasks.Task.Execute()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
>    at InventoryKamera.WeaponScraper+<CatalogueFromBitmapsAsync>d__6.MoveNext()
> 
> Exception Info: System.AggregateException
>    at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetResultCore(Boolean)
>    at InventoryKamera.InventoryKamera.ImageProcessorWorker()
>    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
>    at System.Threading.ThreadHelper.ThreadStart()

**Error Message 2:**
> Faulting application name: InventoryKamera.exe, version: 1.3.16.38641, time stamp: 0x66288a53
> Faulting module name: KERNELBASE.dll, version: 10.0.22621.3733, time stamp: 0x44653e19
> Exception code: 0xe0434352
> Fault offset: 0x000000000005f39c
> Faulting process id: 0x0x3068
> Faulting application start time: 0x0x1DADA92B1CF22C4
> Faulting application path: C:\Users\Paul\Downloads\Genshin_Inventory_KameraV1.3.16\InventoryKamera.exe
> Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
> Report Id: c68a9303-ae07-48ad-8910-49868dd6f65d
> Faulting package full name: 
> Faulting package-relative application ID: 

If you need further infos let me know.

**Comment by falcongoat** [comment]
Can reproduce with exact same errors in Windows Event Log.

OS: Windows 10

Tested resolutions: All 16:9 resolutions, fullscreen and windowed

**Comment by rookiedev007** [comment]
I am currently on Genshin 6.5, OS Windows 11, 1600x900 Windowed, Kamera Version 1.4.3. The same stuff is happening to me, scans 3 weapons and then pauses and crashes. Was this fixed? @taiwenlee

**Comment by taiwenlee** [comment]
> I am currently on Genshin 6.5, OS Windows 11, 1600x900 Windowed, Kamera Version 1.4.3. The same stuff is happening to me, scans 3 weapons and then pauses and crashes. Was this fixed? @taiwenlee 

This sounds like the a character is having a shared name with another character
