### ISSUE TITLE
Character Scanning Error

### ISSUE THREAD

**Issue by IrisSun228** [Andrewthe13th/Inventory_Kamera#533]
### Current Behavior

The scanner does not seem to be able to read character talent levels. After entering the character screen, it manages to read the first character's name, element, level, and constellations, but upon entering the talent screen and opening up the normal attack talent, the InventoryKamera automatically exits the character screen and ends the scan on its own.

I tried this over and over again with the scanner, even on the lowest speed, some with weapons and artifacts scanned as well, some with only characters selected, even going so far as to delete and re-download the application on my device. I've also updated the lookup tables multiple times and changed the starting character to no avail.

Every time I get the same error log, which I have copied down below.

Parameter is not valid.
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   at InventoryKamera.Navigation.CaptureRegion(RECT region, PixelFormat format)
   at InventoryKamera.CharacterScraper.ScanTalents(Character character)
   at InventoryKamera.CharacterScraper.ScanCharacter(String firstCharacter)
   at InventoryKamera.CharacterScraper.ScanCharacters(List`1& Characters)
   at InventoryKamera.InventoryKamera.GatherData()

![Screenshot 2024-09-08 194857](https://github.com/user-attachments/assets/0124fa69-0375-4a6f-91e4-682f3f202a65)
![Screenshot 2024-09-08 195038](https://github.com/user-attachments/assets/54597c3d-daf9-49f9-95ef-0e3407d4c582)
![Screenshot 2024-09-08 195152](https://github.com/user-attachments/assets/810bab52-1e03-4430-916e-d54a7d7467c7)

There also seems to be an error with the artifact scanning, as it auto stops scanning after 200 artifacts (25 rows, or 5 screen scans / scrolls, all 5* & level 20), but that's a separate issue that I believe some others have already raised concerns regarding that situation and I'm more concerned about the character scan error.

This is the error log I'm getting for that is as follows: 

Object reference not set to an instance of an object.
   at InventoryKamera.InventoryScraper.GetPageOfItems(Int32 pageNum, Boolean acceptLess)
   at InventoryKamera.ArtifactScraper.ScanArtifacts(Int32 count)
   at InventoryKamera.InventoryKamera.GatherData()

### Expected Behavior

The scanner continues to scan

### Reproducing a Behavior

Frankly, I'm not sure if it's just an issue with my device or not, but I just ran the scanner as i usually do, but the last time I did so (around 4.6, I believe) this wasn't an issue if I just slowed the scan speed.

### Device OS

Windows 11

### Genshin Impact Version

5.0

### Inventory Kamera Version

1.3.16

### Screen resolution, screen mode, and UI scale

1680x1050 fullscreen

### Evidence

I included my error logs in the Current Behavior sections as well, but here they are:

For character scanning:

Parameter is not valid.
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   at InventoryKamera.Navigation.CaptureRegion(RECT region, PixelFormat format)
   at InventoryKamera.CharacterScraper.ScanTalents(Character character)
   at InventoryKamera.CharacterScraper.ScanCharacter(String firstCharacter)
   at InventoryKamera.CharacterScraper.ScanCharacters(List`1& Characters)
   at InventoryKamera.InventoryKamera.GatherData()

For artifact scanning:

Object reference not set to an instance of an object.
   at InventoryKamera.InventoryScraper.GetPageOfItems(Int32 pageNum, Boolean acceptLess)
   at InventoryKamera.ArtifactScraper.ScanArtifacts(Int32 count)
   at InventoryKamera.InventoryKamera.GatherData()

### Preflight Checklist

- [X] I have checked for similar issues in the issue page, and I have not found any similar to mine.
- [X] I am using the latest version of the scanner.
- [X] I tried setting the scanning delay to maximum, and it still doesn't work.
- [ ] I have attached the video recording to the bug report.
- [X] I have attached the error log to the bug report.
- [X] I am available to later explains the issue.
- [X] I have disabled (or documented) all screen filtering software, plugins, and enhancements while scanning.
- [X] I use default in-game keybindings or have configured keybindings for the scanner.

**Comment by valiantpt** [comment]
Try changing your resolution to 1920x1080 windowed, it seemed to fix the issue (if you still need a fix)

**Comment by IrisSun228** [comment]
> Try changing your resolution to 1920x1080 windowed, it seemed to fix the issue (if you still need a fix)

I changed to a windowed resolution, & everything worked for me, thank you
